Repository kwame-mintah/bionic-speed-reader-browser-extension, pull requests merged in 2022-05, with the labels that each got.

#3 docs(comments): change from single-line comments to multi-line comments
  src/js/bionic-reading-api.js
  src/js/options.js
Labels: documentation

#2 docs(github): create pull request template for repository
  .github/pull_request_template.md
Labels: documentation

#9 fix(options): stop preview text being requested on page load
  src/js/bionic-reading-api.js
Labels: bug

#12 allow users ability to convert a webpage to bionic reading
  README.md
  src/html/options.html
  src/html/response.html
  src/js/axios.min.js
  src/js/axios.min.map
  src/js/background.js
  src/js/bionic-reading-api.js
  src/js/convert.js
Labels: enhancement

#18 Create LICENSE
  LICENSE
Labels: documentation

#31 Fix/color not defined
  src/js/utility.js
Labels: bug

#32 Add bionic link
  src/html/popup.html
Labels: bug
